version: "3.8"

services:
  shiny:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3838"
    env_file:
      - stack.env
    environment:
      APPLICATION_LOGS_TO_STDOUT: "true"
      APP_DATA_DIR: "/srv/shiny-server/data"
    volumes:
      - shiny-data:/srv/shiny-server/data
    restart: always 

volumes:
  shiny-data:
    driver: local